services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - WEBSITE_URL=${WEBSITE_URL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
